--PONER bbdd MODO completo (con REGISTRO TRANSACCIONES)

CREATE DATABASE transacciones

use transacciones

creATE TABLE ALUMNOS
(IDALUMNO INT PRIMARY KEY,
NOMBRE VARCHAR(20))

INSERT INTO ALUMNOS VALUES(1,'GUAN')
INSERT INTO ALUMNOS VALUES(2,'GUAN2')

--BACKUP COMPLETO
INSERT INTO ALUMNOS VALUES(3,'GUAN3')
INSERT INTO ALUMNOS VALUES(4,'GUAN4')

--BACKUP registro

INSERT INTO ALUMNOS VALUES(5,'GUAN5')
INSERT INTO ALUMNOS VALUES(6,'GUAN6')

-- BACKUP registro2

INSERT INTO ALUMNOS VALUES(7,'GUAN7')

-- tiempo 43:23

-- CATASTROFE

DELETE FROM ALUMNOS

SELECT * FROM ALUMNOS
